// <auto-generated />
namespace ProjectManagementSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Entity_Modify : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Entity_Modify));
        
        string IMigrationMetadata.Id
        {
            get { return "201807030737588_Entity_Modify"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
